### ISSUE TITLE
I got the problem

### ISSUE THREAD

**Issue by Leosword** [alessandro308/Speech2Text-Telegram-Bot#4]
java.io.IOException: Cannot run program "opusdec": CreateProcess error=2, O sistema não pode encontrar o arquivo especificado
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at s2t.TranscriptAudio.downloadAndConvert(TranscriptAudio.java:91)
	at s2t.TranscriptAudio.run(TranscriptAudio.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, O sistema não pode encontrar o arquivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more

**Comment by alessandro308** [comment]
Probably this appear because you haven't install dependencies: opusdec. This tool is used to convert the whatsapp format (.opus) to format that Google, Bing and Wit requires. So try to install it and retry.

You can improve this code to convert files without opus-tool. Try to read this line to understand (https://github.com/alessandro308/Speech2Text-Telegram-Bot/blob/a4eb6e48419c8e534cea0fbeaa2a9c997de9a409/src/s2t/TranscriptAudio.java#L91)

**Comment by Leosword** [comment]
Only install on the System? Or need to be on the project?

thanks for help.

**Comment by alessandro308** [comment]
On the system. You need to be able to execute the parameter of exec function previously reported

```
opusdec --rate 16000 "+"audio/"+voice.get("file_id")+".oga"+" "+"audio/"+voice.get("file_id")+".wav"
```

 in your terminal in order to resolve that problem

Of course, if you execute this line on your terminal, you need to substitute voice.get("file_id") with some files and concat the strings

**Comment by Leosword** [comment]
Thanks Alessandro.
